// Generated by CoffeeScript 1.7.1
(function() {
  var createGameBox, lastTime, main, requestAnimFrame;

  createGameBox = function() {
    var canvas, ctx;
    canvas = document.createElement("canvas");
    ctx = canvas.getContext("2d");
    canvas.setAttribute('id', 'game-box');
    canvas.width = 900;
    canvas.height = 500;
    return document.body.appendChild(canvas);
  };

  lastTime = 0;

  main = function() {
    var dt, now;
    now = Date.now();
    dt = (now - lastTime) / 1000.0;
    update(dt);
    render();
    lastTime = now;
    return requestAnimFrame(main);
  };

  requestAnimFrame = function() {
    return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback) {
      return window.setTimeout(callback, 1000 / 60);
    };
  };

  $(function() {
    return createGameBox();
  });

  (function() {
    var load, loading, readyCallbacks, resourceCache;
    resourceCache = {};
    loading = [];
    readyCallbacks = [];
    return load = function(urlOrArr) {
      var url, _i, _len, _results;
      if (urlOrArr instanceof Array) {
        _results = [];
        for (_i = 0, _len = urlOrArr.length; _i < _len; _i++) {
          url = urlOrArr[_i];
          _results.push(_load(url));
        }
        return _results;
      } else {
        return _load(urlOrArr);
      }
    };
  })();

}).call(this);
