// Generated by CoffeeScript 1.7.1
(function() {
  var createGameBox;

  createGameBox = function() {
    var canvas, ctx;
    canvas = document.createElement("canvas");
    ctx = canvas.getContext("2d");
    canvas.setAttribute('id', 'game-box');
    canvas.width = 900;
    canvas.height = 500;
    return document.body.appendChild(canvas);
  };

  $(function() {
    return createGameBox();
  });

}).call(this);
